### ISSUE TITLE
bug in helocon_filter_in

### ISSUE THREAD

**Issue by tsvbrest** [ggrandes/apache24-modules#1]
In my Apache configuration i had big count lines with Segment violation.
I am investigate this troubles and found same bug in helocon_filter_in function.
at line 15106 you have next code:
char *end = memchr(str,  '\r', length - 1 );
Trouble in fact, that length can be zero...
So, i make next fixs:
char *end = NULL;
if( length) end = memchr( str, '\r', length -1 );
Now my troubles is resolved.
Thanks you very match for you module!

**Comment by ggrandes** [comment]
Can you give more info about your configuration? is http(80), https(443)? you have any request to reproduce zero-lengths?

**Comment by ggrandes** [comment]
done in [f24704f]
