### ISSUE TITLE
myfixip + mod security

### ISSUE THREAD

**Issue by ericofusco** [ggrandes/apache24-modules#5]
It seems myfixip doesn't set the variables used by mod security when parsing the agent IP. I'm not sure if it's an issue on myfixip or mod security. I tried to use remoteip as workaround but that didn't work.

Apache 2.4.7
Mod Security 2.7.7

```
<IfModule mod_myfixip.c>
    RewriteIPResetHeader on
    RewriteIPAllow 10.0.0.0/16 127.0.0.1
</IfModule>

<IfModule mod_remoteip.c>
    RemoteIPHeader X-Cluster-Client-Ip
    # Just 10.0.0.0/16 listed on file
    RemoteIPInternalProxyList /etc/apache2/trusted-proxies.lst
</IfModule>
```

Mod security logs showing the correct external IP address on apache logs:

```
Dec  7 19:55:28 dev www_dev[5836]:  [client 54.165.XXX.XXX] ModSecurity: Access denied with code 403 (phase 2). Pattern match ..."
```

Mod security audit logs parsing the load balancer IP instead.

```
--90491855-A--
[07/Dec/2015:19:35:54 +0000] VmXfmn8AAAEAAANSL4MAAABw 10.0.220.75 14882 10.0.220.50 443
--90491855-B--
GET /?test_xss=%3Cscript%3Ealert(1)%3C/script%3E HTTP/1.1
Host: devl
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: pt-BR,pt;q=0.8,en-CA;q=0.6,en;q=0.4,en-US;q=0.2
X-Cluster-Client-Ip: 54.165.XXX.XXX
```

**Comment by ggrandes** [comment]
you don't need mod_remoteip, fixip and remoteip are similar, but different implementation and concept...

**Comment by ericofusco** [comment]
@ggrandes But remoteip doesn't read PROXY headers does it ? It seems mod security reads a field that myfixip doesn't set, but remoteip does. Honestly I'm not sure.

**Comment by ggrandes** [comment]
@ericofusco correct, remoteip don't understand PROXY protocol. But mod_remoteip don't set any header, only read... 
A) Are you sure that mod_security need one http-header? 
B) What config are you using in mod_security?

**Comment by ericofusco** [comment]
Hi @ggrandes ,

Sorry the delay.

A) Mod security doesn't read any HTTP headers, but it seems mod security had some work done to work with remoteip to set a new remote_addr.
B) I'm using default configuration, nothing unusual.

Check these lines on mod security, maybe I can make some changes to mod security to make it work with myfixip and/or we can make changes to myfixip to work with mod security.

Mod Security (2.9.0);

apache2/mod_security2.c

```
    static const char *const postread_beforeme_list[] = {
        "mod_rpaf.c",
        "mod_rpaf-2.0.c",
        "mod_extract_forwarded.c",
        "mod_extract_forwarded2.c",
        "mod_remoteip.c",
        "mod_custom_header.c",
        "mod_breach_realip.c",
        "mod_breach_trans.c",
        "mod_unique_id.c",
        NULL 
    }; 
```

apache2/re_variables.c

```
#if !defined(MSC_TEST)
#if AP_SERVER_MAJORVERSION_NUMBER > 1 && AP_SERVER_MINORVERSION_NUMBER > 3
    if (ap_find_linked_module("mod_remoteip.c") != NULL) {
        if(msr->r->useragent_ip != NULL) msr->remote_addr = apr_pstrdup(msr->mp, msr->r->useragent_ip);
        return var_simple_generate(var, vartab, mptmp, msr->remote_addr);
    }    
#endif
#endif
```

Clearly there is a dependence on remoteip to set another remote_addr, but I believe myfixip doesn't set useragent_ip either. Maybe changes need to be done on both ends.

Please let me know your thoughts.

Thanks.

**Comment by ggrandes** [comment]
Ok, try this change in mod_myfixip.c (version 1.3), without load mod_remoteip:

```diff
- ap_hook_post_read_request(post_read_handler, NULL, NULL, APR_HOOK_FIRST);
+ ap_hook_post_read_request(post_read_handler, NULL, NULL, APR_HOOK_REALLY_FIRST - 1);
```
give me your feedback!

**Comment by ggrandes** [comment]
@ericofusco I released a new version (1.4), try with this (without mod_remoteip) and give me your feedback :-)

**Comment by ericofusco** [comment]
Hey @ggrandes,

Thanks a lot for the update.

Unfortunately it didn't work. Mod security still parses the load balancer IP. Although I changed modsecurity and updated the condition from the block I posted before to the one below.

```
if (ap_find_linked_module("mod_remoteip.c") != NULL || ap_find_linked_module("mod_myfixip.c") != NULL)
```

That did the trick. Does that make sense to you ? I believe myfixip only changes useragent_ip just like remoteip. If that's the case I'll just do pull request to mod security to load myfixip before and add this condition.

Please let me know your thoughts.

Thanks.

**Comment by ggrandes** [comment]
Hi @ericofusco , this seem correct aproach!

**Comment by ericofusco** [comment]
Thanks a lot @ggrandes. I'll see if I can push this update to modsecurity. Task can be closed.
