### ISSUE TITLE
send-proxy-v2-ssl-cn

### ISSUE THREAD

**Issue by swenske** [ggrandes/apache24-modules#9]
Hi,

Is your module supposed to work with send-proxy-v2-ssl-cn option ?

https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#5.2-send-proxy-v2-ssl-cn

Best Regards;
Sebastian W.

**Comment by swenske** [comment]
I get an ssl handshake failure when I try to enable send-proxy-v2(-ss(-cn)) option in HaProxy

**Comment by ggrandes** [comment]
This module was intended for use in AWS-ELB. Only [version 1](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html) is implemented.

> Elastic Load Balancing uses Proxy Protocol version 1, which uses a human-readable header format.
